// Level 5 Test Deployment - 10 nodes

CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-f1f820614de1", eventType: "BREACH_REPORT", timestamp: "2025-10-27T14:30:43.077922", source: "DHS", severity: "HIGH", cvssScore: 7.0, epssScore: 0.603, affectedSectors: ["Chemical"], affectedAssets: 4209, fearFactor: 6.9, realityFactor: 5.1, fearRealityGap: 1.8, mediaArticles: 270, socialAmplification: 100, description: "HIGH vulnerability scan affecting Chemical sectors", metadata: "{\"confidence\": 0.98, \"verified\": true, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-7118ae5ee36e", eventType: "RANSOMWARE_ATTACK", timestamp: "2025-08-24T09:56:43.077922", source: "X-Force", severity: "HIGH", cvssScore: 7.5, epssScore: 0.543, affectedSectors: ["Financial"], affectedAssets: 98888, fearFactor: 6.9, realityFactor: 5.4, fearRealityGap: 1.5, mediaArticles: 2, socialAmplification: 2, description: "HIGH malware detection affecting Financial sectors", metadata: "{\"confidence\": 0.89, \"verified\": true, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-69ed23f07031", eventType: "VULNERABILITY_SCAN", timestamp: "2025-08-17T21:57:43.077922", source: "FBI", severity: "HIGH", cvssScore: 7.3, epssScore: 0.614, affectedSectors: ["Government"], affectedAssets: 36919, fearFactor: 6.7, realityFactor: 6.2, fearRealityGap: 0.5, mediaArticles: 68, socialAmplification: 100, description: "HIGH insider threat affecting Government sectors", metadata: "{\"confidence\": 0.94, \"verified\": false, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-0fbd5429f763", eventType: "VULNERABILITY_SCAN", timestamp: "2025-08-22T16:23:43.077922", source: "X-Force", severity: "LOW", cvssScore: 2.5, epssScore: 0.084, affectedSectors: ["Water"], affectedAssets: 74463, fearFactor: 1.4, realityFactor: 1.4, fearRealityGap: 0.0, mediaArticles: 0, socialAmplification: 0, description: "LOW insider threat affecting Water sectors", metadata: "{\"confidence\": 0.61, \"verified\": false, \"actionable\": false}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-1cb90db22925", eventType: "SUPPLY_CHAIN", timestamp: "2025-06-19T01:47:43.077922", source: "SecurityFeed", severity: "CRITICAL", cvssScore: 9.8, epssScore: 0.738, affectedSectors: ["Communications"], affectedAssets: 44455, fearFactor: 8.3, realityFactor: 8.2, fearRealityGap: 0.1, mediaArticles: 1, socialAmplification: 0, description: "CRITICAL supply chain affecting Communications sectors", metadata: "{\"confidence\": 0.67, \"verified\": true, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-4c0685fbaa8e", eventType: "BREACH_REPORT", timestamp: "2025-06-07T08:09:43.077922", source: "Mandiant", severity: "HIGH", cvssScore: 7.5, epssScore: 0.555, affectedSectors: ["Commercial"], affectedAssets: 24325, fearFactor: 6.5, realityFactor: 6.5, fearRealityGap: 0.0, mediaArticles: 0, socialAmplification: 0, description: "HIGH breach report affecting Commercial sectors", metadata: "{\"confidence\": 0.75, \"verified\": true, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-479800d7ab84", eventType: "INSIDER_THREAT", timestamp: "2025-09-05T16:06:43.077922", source: "CISA", severity: "MEDIUM", cvssScore: 4.8, epssScore: 0.169, affectedSectors: ["Food", "Defense", "Manufacturing"], affectedAssets: 26665, fearFactor: 3.9, realityFactor: 3.7, fearRealityGap: 0.2, mediaArticles: 39, socialAmplification: 59, description: "MEDIUM zero day affecting Food, Defense sectors", metadata: "{\"confidence\": 0.94, \"verified\": true, \"actionable\": false}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-86fa25204380", eventType: "THREAT_INTEL", timestamp: "2025-09-20T05:41:43.077922", source: "Talos", severity: "CRITICAL", cvssScore: 9.7, epssScore: 0.717, affectedSectors: ["Emergency", "Dams", "Transportation"], affectedAssets: 79574, fearFactor: 8.4, realityFactor: 7.6, fearRealityGap: 0.8, mediaArticles: 63, socialAmplification: 21, description: "CRITICAL zero day affecting Emergency, Dams sectors", metadata: "{\"confidence\": 0.91, \"verified\": false, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-3bfc45bb419c", eventType: "SUPPLY_CHAIN", timestamp: "2025-08-30T22:01:43.077922", source: "FireEye", severity: "HIGH", cvssScore: 8.3, epssScore: 0.503, affectedSectors: ["Commercial"], affectedAssets: 90420, fearFactor: 7.9, realityFactor: 5.1, fearRealityGap: 2.8, mediaArticles: 17, socialAmplification: 11, description: "HIGH cve disclosure affecting Commercial sectors", metadata: "{\"confidence\": 0.78, \"verified\": true, \"actionable\": true}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (ie:InformationEvent:Event:Information:RealTime:Level5 {eventId: "IE-f5faa5b12ef3", eventType: "PATCH_RELEASE", timestamp: "2025-08-10T02:04:43.077922", source: "CISA", severity: "MEDIUM", cvssScore: 6.1, epssScore: 0.25, affectedSectors: ["Water", "Manufacturing"], affectedAssets: 91204, fearFactor: 4.1, realityFactor: 3.1, fearRealityGap: 1.0, mediaArticles: 10, socialAmplification: 11, description: "MEDIUM patch release affecting Water, Manufacturing sectors", metadata: "{\"confidence\": 0.65, \"verified\": false, \"actionable\": false}", nodeType: "InformationEvent", level: 5, created: datetime()});
CREATE (tf:ThreatFeed:DataSource:Integration:RealTime:Level5 {feedId: "TF-001", feedName: "CISA_AIS", feedType: "STIX", reliability: 0.95, latency: 2, coverage: 0.6, lastUpdate: "2025-11-22T09:48:43.146172", eventsProcessed: 91038, configuration: "{\"endpoint\": \"https://ais.cisa.gov/api/v2\", \"auth\": \"api_key\", \"format\": \"STIX 2.1\", \"update_frequency\": \"5 minutes\"}", nodeType: "ThreatFeed", level: 5, created: datetime()});

// Validate test deployment
MATCH (n:Level5) RETURN count(n) as count;